### PR TITLE
Issue #13, Issue #17, Issue #25, other improvements.

### PR DESCRIPTION
**Pull request by bstump**
Manage multiple subscriptions (Issue #13). Confirmation dialog for subscription cancellation (Issue #17). Disabled refund button on charges already refunded (Issue #25). Confirmation dialog for refunds.

### CODE REVIEW

**Comment by bstump** [comment]
Could we get this merged into the master branch, please?

**Comment by mikoop79** [comment]
Any chance this could be merged into master?

**Comment by bstump** [comment]
I've asked several times, even emailed all contributors, no response... Starting to wonder if this repo is going to be updated outside of a couple times a year. :-/

**Comment by mikoop79** [comment]
Thanks!

**Pull request closed without merging**
