### PR TITLE
Close #9

### LINKED ISSUE #9: Unable to specify subscription plan name
In `CashierToolController` in the `user` method it's calling `$billable->subscription()` and that method defaults the plan to `default`. Would it be possible for you to add a configuration option for this - something like `$billable->subscription(config('nova-cashier-manager.plan', 'default'))`.

### PR DESCRIPTION
**Pull request by jameslkingsley**

### CODE REVIEW

**Comment by jameslkingsley** [comment]
Oh I messed up, this includes the other PR as well. I'll just close the other one.

**Comment by jameslkingsley** [comment]
Tested on Nova 1.0.5, all working.

**Comment by jameslkingsley** [comment]
Tbh this should cater for multiple subscription plans but 🤷‍♂️

**Comment by themsaid** [comment]
Thank you, this is great :)

**Pull request merged**
